<a href="https://colab.research.google.com/github/gpugovka/ML-stuff/blob/main/Mini_Project_Part3_Erin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Part 3: Combining DataFrames, Text & Date Methods in Pandas**

### **Dataset Introduction**

In this project, we will work with the Palmer Penguins dataset, which contains measurements of penguins observed on islands near Antarctica.

Please download the dataset [penguins.csv](https://drive.google.com/file/d/1dv8A8v_sdf29p1At40S7KBslJPmBA3e9/view?usp=sharing) or from canvas.

### **Dataset Description**

Each row represents a penguin, and columns include:

- species – Penguin species
- island – Island where the penguin was found
- bill_length_mm – Bill length (mm)
- bill_depth_mm – Bill depth (mm)
- flipper_length_mm – Flipper length (mm)
- body_mass_g – Body mass (grams)
- sex – Sex of the penguin

Some values are missing, which makes this dataset ideal for practicing missing data handling.

### **Load the Dataset**

In [1]:
# Load the Dataset: Begin by loading the penguins.csv dataset into a pandas DataFrame.

import pandas as pd
import numpy as np

penguins = pd.read_csv("penguins.csv")

### **Part 1 — Basic Pandas Commands**

Q1. Display the dataset information.

In [4]:
penguins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                334 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [3]:
# DO NOT RUN THIS

Q2. Display the number of unique species and unique islands.

In [8]:
penguins["species"].unique().shape[0]

3

In [9]:
penguins["island"].unique().shape[0]

3

In [ ]:
# DO NOT RUN THIS

3

In [ ]:
# DO NOT RUN THIS

3

### **Part 2 — GroupBy Basics**

Q3. Compute the average body mass for each species.

In [10]:
penguins.groupby("species")['body_mass_g'].mean()

species
Adelie       3700.662252
Chinstrap    3733.088235
Gentoo       5076.016260
Name: body_mass_g, dtype: float64

In [ ]:
# DO NOT RUN THIS

species
Adelie       3700.662252
Chinstrap    3733.088235
Gentoo       5076.016260
Name: body_mass_g, dtype: float64

Q4. Compute the average flipper length for each island.

In [11]:
penguins.groupby('island')['flipper_length_mm'].mean()

island
Biscoe       209.706587
Dream        193.072581
Torgersen    191.196078
Name: flipper_length_mm, dtype: float64

In [ ]:
# DO NOT RUN THIS

island
Biscoe       209.706587
Dream        193.072581
Torgersen    191.196078
Name: flipper_length_mm, dtype: float64

Q5. For each species, find the minimum, maximum, and mean of bill_length_mm.

In [2]:
penguins.groupby("species")["bill_length_mm"].agg(['min', 'max', 'mean'])

            min   max       mean
species
Adelie     32.1  46.0  38.791391
Chinstrap  40.9  58.0  48.833824
Gentoo     40.9  59.6  47.504878

In [ ]:
# DO NOT RUN THIS

            min   max       mean
species
Adelie     32.1  46.0  38.791391
Chinstrap  40.9  58.0  48.833824
Gentoo     40.9  59.6  47.504878

Q6. For each species–island combination, find the number of non-missing body mass measurements.

In [6]:
penguins.groupby(["species", "island"])['body_mass_g'].count()

species    island
Adelie     Biscoe        44
           Dream         56
           Torgersen     51
Chinstrap  Dream         68
Gentoo     Biscoe       123
Name: body_mass_g, dtype: int64

In [ ]:
# DO NOT RUN THIS

species    island
Adelie     Biscoe        44
           Dream         56
           Torgersen     51
Chinstrap  Dream         68
Gentoo     Biscoe       123
Name: body_mass_g, dtype: int64

Q7. Identify the species with the largest average body mass.

In [30]:
avg_masses = penguins.groupby("species")['body_mass_g'].mean().copy()
avg_masses.idxmax()

'Gentoo'

In [29]:
# penguins.join(avg_masses.rename('avg_body_mass_g'),how='left', on="species")

In [ ]:
# DO NOT RUN THIS

'Gentoo'

Q8. Sort islands by descending average flipper length.

In [34]:
penguins.groupby("island")['flipper_length_mm'].mean().sort_values(ascending=False)

island
Biscoe       209.706587
Dream        193.072581
Torgersen    191.196078
Name: flipper_length_mm, dtype: float64

In [ ]:
# DO NOT RUN THIS

island
Biscoe       209.706587
Dream        193.072581
Torgersen    191.196078
Name: flipper_length_mm, dtype: float64

Q9.Find species–island groups with at least 20 penguins.

In [60]:
from numpy._core.defchararray import count
from ast import Del

species_island_count = penguins.groupby(['species','island']).count()
species_island = species_island_count[species_island_count['bill_length_mm'] > 20]['bill_length_mm'].rename('count')
species_island_x_penguins = penguins.join(species_island, how='left', on=['species','island'])
species_island_x_penguins_filtered = species_island_x_penguins[species_island_x_penguins['count'] > 20]
del species_island_x_penguins_filtered['count']
species_island_x_penguins_filtered

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [ ]:
# DO NOT RUN THIS

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

Q10. For each species, compute:

- average body mass
- average flipper length

In [62]:
penguins.groupby("species")[["body_mass_g","flipper_length_mm"]].mean()

           body_mass_g  flipper_length_mm
species
Adelie     3700.662252         189.953642
Chinstrap  3733.088235         195.823529
Gentoo     5076.016260         217.186992

In [ ]:
# DO NOT RUN THIS

           body_mass_g  flipper_length_mm
species
Adelie     3700.662252         189.953642
Chinstrap  3733.088235         195.823529
Gentoo     5076.016260         217.186992

Q11. For each island, compute:

- count of penguins
- mean body mass
- standard deviation of body mass

In [64]:
penguins.groupby("island")["body_mass_g"].agg(['count','mean','std'])

           count         mean         std
island
Biscoe       167  4716.017964  782.855743
Dream        124  3712.903226  416.644112
Torgersen     51  3706.372549  445.107940

In [ ]:
# DO NOT RUN THIS

           count         mean         std
island
Biscoe       167  4716.017964  782.855743
Dream        124  3712.903226  416.644112
Torgersen     51  3706.372549  445.107940

### **Part 3 — Combining DataFrames + GroupBy**

Q12. Create the following penguin_regions dataframe and merge with penguins.



```
{
    'island': ['Biscoe', 'Dream', 'Torgersen'],
    'region': ['Antarctica', 'Antarctica', 'Antarctica']
}
```

In [71]:
regions_dict = {
    'island': ['Biscoe', 'Dream', 'Torgersen'],
    'region': ['Antarctica', 'Antarctica', 'Antarctica']
}
regions = pd.DataFrame(regions_dict)
penguins_x_regions = penguins.join(regions.set_index('island'), on='island',how='outer')
penguins_x_regions

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,region
20,Adelie,Biscoe,37.8,18.3,174.0,3400.0,FEMALE,Antarctica
21,Adelie,Biscoe,37.7,18.7,180.0,3600.0,MALE,Antarctica
22,Adelie,Biscoe,35.9,19.2,189.0,3800.0,FEMALE,Antarctica
23,Adelie,Biscoe,38.2,18.1,185.0,3950.0,MALE,Antarctica
24,Adelie,Biscoe,38.8,17.2,180.0,3800.0,MALE,Antarctica
...,...,...,...,...,...,...,...,...
127,Adelie,Torgersen,41.5,18.3,195.0,4300.0,MALE,Antarctica
128,Adelie,Torgersen,39.0,17.1,191.0,3050.0,FEMALE,Antarctica
129,Adelie,Torgersen,44.1,18.0,210.0,4000.0,MALE,Antarctica
130,Adelie,Torgersen,38.5,17.9,190.0,3325.0,FEMALE,Antarctica
131,Adelie,Torgersen,43.1,19.2,197.0,3500.0,MALE,Antarctica

Q13. Compute the average body mass per region.

In [72]:
penguins_x_regions.groupby("region")['body_mass_g'].mean()

region
Antarctica    4201.754386
Name: body_mass_g, dtype: float64

In [ ]:
# DO NOT RUN THIS

region
Antarctica    4201.754386
Name: body_mass_g, dtype: float64

Q14.Compute the average body_mass_g grouped by species, and then compute the overall average body_mass_g without grouping.

- Why are the species-level averages different from the overall average?
- What does this tell you about how groupby() changes the interpretation of results?

In [75]:
penguins['body_mass_g'].mean()

np.float64(4201.754385964912)

In [73]:
penguins.groupby("species")['body_mass_g'].mean()

species
Adelie       3700.662252
Chinstrap    3733.088235
Gentoo       5076.016260
Name: body_mass_g, dtype: float64

In [ ]:
# DO NOT RUN THIS

np.float64(4201.754385964912)

In [ ]:
# DO NOT RUN THIS

species
Adelie       3700.662252
Chinstrap    3733.088235
Gentoo       5076.016260
Name: body_mass_g, dtype: float64

Your Explanation:

They are different because the first one calculates the average across all the rows in the data frame, and if we use groupby it calculates averages only over the selected group of each species.

The fact that it does not macth means that the distribution of the mass accross the species is not the same, and some species are heavier than others on average.

### **Part 4 — GroupBy with Text Methods**

Q15. Create species_lower with lowercase species names.

In [ ]:
# DO NOT RUN THIS

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_lower
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,adelie
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,adelie
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,adelie
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,adelie
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,adelie

Q16. After creating the species_lower column, you want to verify that converting text to lowercase did not change the number of observations for each species.

Compute the number of penguins for each value in species_lower.

In [ ]:
# DO NOT RUN THIS

species_lower
adelie       152
gentoo       124
chinstrap     68
Name: count, dtype: int64

Q17. Create penguin_observations, with the following data.

observation_date': '2019-01-15', '2019-02-20', '2020-01-05', '2020-03-18'

In [ ]:
# DO NOT RUN THIS

   penguin_id observation_date
0           1       2019-01-15
1           2       2019-02-20
2           3       2020-01-05
3           4       2020-03-18

Q19. Convert observation_date to datetime and extract year.

In [ ]:
# DO NOT RUN THIS

   penguin_id observation_date  year
0           1       2019-01-15  2019
1           2       2019-02-20  2019
2           3       2020-01-05  2020
3           4       2020-03-18  2020

Q20. Merge with original penguins dataframe and show the head.

In [ ]:
# DO NOT RUN THIS

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_lower,penguin_id,observation_date,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,adelie,0,2019-01-15,2019.0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,adelie,1,2019-02-20,2019.0
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,adelie,2,2020-01-05,2020.0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,adelie,3,2020-03-18,2020.0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,adelie,4,NaT,NaN